# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codesample', '0003_auto_20160813_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 13, 14, 11, 14, 651919)),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='name',
            field=models.CharField(default=b'20160813_141114', max_length=20),
        ),
    ]
