# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codesample', '0004_auto_20160813_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 10, 59, 12, 593689)),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='name',
            field=models.CharField(default=b'20160814_105912', max_length=20),
        ),
    ]
