# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codesample', '0017_auto_20160814_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 12, 14, 30, 647537)),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='name',
            field=models.CharField(default=b'20160814_121430', max_length=20),
        ),
    ]
