# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 04:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Codesample', '0027_auto_20160816_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 17, 4, 50, 2, 968925)),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='name',
            field=models.CharField(default=b'20160817_045002', max_length=20),
        ),
    ]
